### PR TITLE
Geolocation on registration

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by ppapadeas** [comment]
getCurrentPosition should be invoked in /register/ automatically but be opt-in in profile edit.

**Comment by comzeradd** [comment]
You mean "shouldn't"? Because you get to /register/ before having an option to edit your profile.

**Comment by ppapadeas** [comment]
It _should_ be automatic in /register/ (to help you out with those fields) but not automatic when you edit your profile (you might want to change sth else)

**Comment by comzeradd** [comment]
You're right. I forgot we use the same template for both registration and profile_edit. Reworking on that.

**Comment by comzeradd** [comment]
Now it's better. No intrusive geolocation. You have to opt-in. Of course it needs some css love :-)

**Pull request closed without merging**
